### ISSUE TITLE
ldap-abfrage ldap_admins

### ISSUE THREAD

**Issue by j-b-grenouille** [c-base/cbmi#13]
die Liste bei der Uebersicht, wer Passwoerter                                                                                                                                                           
setzen kann, scheint hart codiert zu sein.

bitte die Gruppe 

`cn=ldap_admins,ou=groups ...`

abfragen

**Comment by cmile** [comment]
wurde angepasst in 3589cd0c48fee6a842017202fb4385f8bd1c1e16
