### ISSUE TITLE
Emaileinstellung und forward

### ISSUE THREAD

**Issue by c-MM** [c-base/cbmi#8]
Wir haben in der cbaseMember objectclass ein preferredEmail Attribut. Ich wuerde das gerne benutzen um mailforwards zu ermoeglichen, ohne sich auf dem Mailserver einen filter clickern zu muessen.

Ich koennte mir das im Interface so vorstellen, dass man einen Haken setzen kann fuer "forward", dann taucht ein Feld auf, in dem man die email-Adresse eingeben kann und die wird dann auf dem ldap-Server gesetzt. Wenn man den Haken entfernt, wird das Attribut wieder auf "leer" gesetzt.

Auf dem Mailserver werte ich aus, ob das Feld einen Wert enthaelt und wenn ja, dann schicke ich die Mails an die Adresse weiter.

Das Feld koennte beim anclicken von "forward" aus dem Attribut externalEmail gefuellt werden.

Achso, schick faende ich es auch, wenn ldap_admins diese Option auch bekommen, wenn sie einem user das Passwort setzen, dann koennte das in einem Rutsch gehen.

**Comment by c-MM** [comment]
Grund dafuer ist, das ich gerade dabei bin den Mailserver auf die neue Hardware umzuziehen und mir aufgefallen ist, dass wir viele member haben, die sich noch nie auf dem Mailserver angemeldet haben. 

Momentane Statistik:
c-mail:~# ~/unusedmailboxes.sh
users: 211 mails: 1573533

**Comment by uwekamper** [comment]
Einjebaut.
